[project]
name = "tm_ai_assistant"
authors = [
    { name = "Fertile Green Industries Pvt Ltd", email = "shivaabhiramreddy@gmail.com" }
]
description = "AI Business Assistant for Truemeal Feeds ERP"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core:buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0"
erpnext = ">=15.0.0"
